<template>
  <div class=" bg-yellow-300 grid grid-cols-12 w-full  ">
<div class=" bg-purple-300 col-span-3  py-10">
  <div class=" fixed">
    The place
  </div>
</div>

<div class=" bg-green-300 col-span-9 h- w-full flex">
  <div class=" overflow-y-auto w-full">
    <ul>
      <li>
        <p>
          Hellow Products
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
      <li>
        <p>
          HellowHellow
        </p>
      </li>
    </ul>
  </div>
</div>
    
  </div>
</template>

<script>
export default {

}
</script>

<style>

</style>